### ISSUE TITLE
Define new Cards sheets

### ISSUE THREAD

**Issue by JPMeehan** [MetaMorphic-Digital/complete-card-management#2]
Use AppV2 to make new default Deck, Hand, and Pile sheets. 

All Cards
- Provide configuration of own properties (try using FormField helper)
- Display list of cards & implement DragDrop handling
- Reset
- Save

Individual sheets:

- [x] Deck: Shuffle and Deal (#16)
- [x] Hand: Draw and Pass (#18)
- [x] Pile: Shuffle and Pass (#18)
